apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
spec:	
  type: NodePort
  ports:	
  - port: 8080
    targetPort: 80	
    protocol: TCP
    name: http
  selector:	
    app: guestbook-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: sudhakar678/nginx-demo:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
